version: "3"

services:
  nllb-translate:
    container_name: nllb-translate
    build: .
    restart: always
    ports:
      - 5001:5001
    volumes:
      - ./nllb_serve:/app/nllb_serve
    entrypoint: [ "gunicorn" ]
    command:
      [
        "nllb_serve.app:app",
        "-b",
        "0.0.0.0:5001",
        "-k",
        "gevent",
        "-w",
        "4",
        "--threads",
        "8",
        "--timeout",
        "6000"
      ]
